apiVersion: apps/v1
kind: Deployment
metadata:
  name: currency-conversion-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: currency-conversion-service
  template:
    metadata:
      labels:
        app: currency-conversion-service
    spec:
      containers:
      - name: traveler
        image: tusharghadge/currency-conversion-service:1.0.0
        env:
          - name: SPRING_CLOUD_CONFIG_URI
            value: http://config-server.default.svc.cluster.local:8888
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
