apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-naming-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-naming-server
  template:
    metadata:
      labels:
        app: eureka-naming-server
    spec:
      containers:
      - name: eureka-server
        image: tusharghadge/eureka-naming-server:1.0.0
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 8761
